### ISSUE TITLE
Failed to read credentials

### ISSUE THREAD

**Issue by japborst** [kevlened/fireway#1]
I'm trying to run migration script, but unfortunately it cannot read my credentials.

Currently using
```cmd
set GOOGLE_APPLICATION_CREDENTIALS="%cd%\google-services.json"
fireway migrate
```

results in
```
ERROR: Failed to read credentials from file "C:\Users\[...]\google-services.json": Error: ENOENT: no 
such file or directory, open '"C:\Users\[...]\google-services.json"
```

Also when setting a relative path (they're in the same folder) `set GOOGLE_APPLICATION_CREDENTIALS="google-services.json"` does not fix it

**Comment by japborst** [comment]
Apparently the quotes were in the way, this did the trick
```cmd
set GOOGLE_APPLICATION_CREDENTIALS=%cd%\google-services.json
fireway migrate
```

After that, worked smoothly! 👍

**Comment by kevlened** [comment]
Glad you worked it out 💯
