### ISSUE TITLE
Parses hidden migration files and errors

### ISSUE THREAD

**Issue by bdiz** [kevlened/fireway#12]
vi creates .*swp files while editing. So when I'm developing the migration script and I run fireway with --dryrun, I get the following error:

`ERROR: Both v0.0.1__move-data-from-user-to-profile.js and .v0.0.1__move-data-from-user-to-profile.js.swp have the same version`

My expectation is that files with a leading `.` would be ignored.

**Thanks for this tool!** I'm not sure how database migrations is completely ignored by the firebase CLI tool / firestore team.

**Comment by kevlened** [comment]
Thanks for the feedback. This is fixed in `0.4.0`.
