### ISSUE TITLE
use with the firestore emulator

### ISSUE THREAD

**Issue by kiptoomm** [kevlened/fireway#16]
Is there any way to use this library against a local instance of firestore running in the emulator? I'd love to test migration scripts against my local instance running at `http://localhost:4000/firestore` but when I do:
`fireway migrate`

I get:
```
Found 2 migration files
ERROR: 9 FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.
```

I thought that maybe it needs the `--projectId` option but I wouldn't know which 'project' to use since the target database is on a [locally] emulated instance. Any ideas?

**Comment by kevlened** [comment]
There is! We do this with to test `fireway` itself. `fireway` is built on [the firestore node library](https://www.npmjs.com/package/@google-cloud/firestore). If you [define `FIRESTORE_EMULATOR_HOST` like we do here](https://github.com/kevlened/fireway/blob/master/package.json#L25), the firestore node library will connect to your local instance ([source](https://firebase.google.com/docs/emulator-suite/connect_firestore)).

**Comment by kiptoomm** [comment]
> There is! We do this to test `fireway` itself. `fireway` is built on [the firestore node library](https://www.npmjs.com/package/@google-cloud/firestore). If you [define `FIRESTORE_EMULATOR_HOST` like we do here](https://github.com/kevlened/fireway/blob/master/package.json#L25), the firestore node library will connect to your local instance ([source](https://firebase.google.com/docs/emulator-suite/connect_firestore)). You shouldn't need a `--projectId`.

Great, thank you! I went ahead and made a PR to improve the docs: https://github.com/kevlened/fireway/pull/17

**Comment by kevlened** [comment]
Thanks for the contribution!
