### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by dzbrozek** [kevlened/fireway#25]
I'm getting `Unexpected token '.'` when running `npx fireway`. Version `0.4.2` is the latest working version for me.

**Comment by kevlened** [comment]
Which version of node are you running?

**Comment by kevlened** [comment]
`0.5.4` is now published without the optional chaining operators. I tested it with Node v10.24.1. Let me know if that resolves your issue.

**Comment by kevlened** [comment]
Thanks for reporting. I'll assume your issue is resolved. Feel free to comment if not.
