### ISSUE TITLE
"Unexpected token ." when running fireway

### ISSUE THREAD

**Issue by optimistiks** [kevlened/fireway#26]
Hi! Thanks for the library. Unfortunately, I run into an issue when running `fireway migrate`

```
.nvm/versions/node/v10.22.0/lib/node_modules/fireway/src/index.js:31
		while (this._fireway_queue?.length) {
		                           ^

SyntaxError: Unexpected token .
```

Does it mean only Node.js versions that support optional chaining are supported?

**Comment by kevlened** [comment]
Apologies. I ran my tests in Node 14. I've removed the optional chaining operators and tested down to Node 10.

I released `1.0.1` to fix the issue. Thanks for reporting. If you continue to have issues, I'll reopen this issue.
