### ISSUE TITLE
Fireway collection is updated to last migration on dryrun

### ISSUE THREAD

**Issue by Nicholaiii** [kevlened/fireway#9]
This means we need to clear the Fireway collection whenever we want to test the migrations. This is a huge hassle.

**Comment by kevlened** [comment]
If `dryrun` makes calls to the db, it's a bug. Is this a problem with 0.2.3?

**Comment by Nicholaiii** [comment]
I took a deep dive. It happens because you monkeypatch google firestore functions, spefically WriteBatch.commit_, but since this is an internal function it's not guaranteed by the project to remain consistent so when you bumped Firestore to version 4, it is no longer there, they just use commit() now.

**Comment by Nicholaiii** [comment]
This also means any potential write operation (not just the Fireway collection) in fireway@0.3.0 is performed regardless of dryrun.

**Comment by kevlened** [comment]
Ah, I checked quickly before publishing and saw [`this._commit()`](https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/write-batch.ts#L571), which is close, but certainly not `this.commit_()`.

Fixing. Thanks for the heads up.

**Comment by kevlened** [comment]
Resolved by 0.3.1
